s = input("Enter a string: ")
char_to_replace = input("Enter the word to replace: ")
replacement_char = input("Enter the replacement word: ")
result = s.replace(char_to_replace, replacement_char)
print(f"Modified string: {result}")